services:
  - type: web
    name: mi-plataforma-docente
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://usuario:password@host.neon.tech/dbname"
